### ISSUE TITLE
is it possible to get the content size of the final stream

### ISSUE THREAD

**Issue by ocylib** [redbrain/ytdl-core-muxer#13]
is it possible to get the content size of the final stream.i'd like to play the final stream on a web instead of download it to a file. it can play now but can't seek in the player, so i need the content size as content-lenth in header and return a 206 code to ckeck if can seek in the player

**Comment by redbrain** [comment]
I don't think the final size of the stream can be known beforehand because it's created on-the-fly.
You can get a non-exact estimate by taking the sum of the sizes of the highestvideo and highestaudio sources.

**Comment by ocylib** [comment]
thanks, I will try
